### ISSUE TITLE
[rc1] alias ~ is all broken.

### ISSUE THREAD

**Issue by jsnick** [nuxt/nuxt.js#1173]
I use alias '~' in my project.

for example,
### pages/index.vue
```
import Loading from '~/components/Loading'
import Errors from '~/components/Errors'
import ProjectListTable '~/containers/ProjectListTable'
...
```
but all is error like `Cannot find module '~/components/Loading' from '/path/to/project'`.

Is there any change about this ?

**Comment by pi0** [comment]
As long as you use `~/components` (not `~components/`) there shouldn't be any breaking changes at least with Nuxt webpack config. Does this issues happens with adding `.vue` extention too?

```js
import Loading from '~/components/Loading.vue'
import Errors from '~/components/Errors.vue'
import ProjectListTable '~/containers/ProjectListTable.vue'
```

**Comment by jsnick** [comment]
there is no issue with this if I add `.vue` extension or just changing `~` to `../`,

**Comment by pi0** [comment]
We are just using same [webpack config](https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/webpack/base.config.js#L47) for aliases as before.

**Comment by jsnick** [comment]
But it works in 1.0.0-alpha1, too

**Comment by pi0** [comment]
That's strange all with your project. It should be working on `rc1` too. See this live example:

https://psychedelic-acoustic.glitch.me
https://glitch.com/edit/#!/psychedelic-acoustic

**Comment by jsnick** [comment]
Sincerely sorry.
After I debug, the reason why this issue happen is to use https://github.com/kolodny/wavy in my node project for require('~') alias.
I think this conflict happen as the version of something about vue-server-renderer (e.g. webpack or babel..) is up.
Anyway, It works if I remove anything about https://github.com/kolodny/wavy or change `~` to another alias in `*.vue`.

Thanks for helping.

**Comment by pi0** [comment]
Your welcome. If you have conflicts with `~` now nuxt supports `@` as alternative too :)

**Comment by awronski** [comment]
Hi @pi0 

I have the same problem. After upgrade from alfa5 to rc2 ```~components``` does not work.
Of course I will replace it to ```~/components``` and it will build.

But it is confusing. For example for styles I still need to import as ```@import "~assets/colors"``` not ```~/assets```.

Could you make it consistent everywhere?
