### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: _consola2.default.withTag is not a function

### ISSUE THREAD

**Issue by Mikkou** [nuxt/nuxt.js#4352]
Have this error

`(node:17818) UnhandledPromiseRejectionWarning: TypeError: _consola2.default.withTag is not a function
    at Object.<anonymous> (/home/mikkou/PhpstormProjects/5element-front/node_modules/webpackbar/dist/utils/cli.js:29:53)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mikkou/PhpstormProjects/5element-front/node_modules/webpackbar/dist/reporters/fancy.js:11:12)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
(node:17818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17818) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

after upgrade nuxt from 2.0.0 to 2.3.1

who know how this to fix?

**Comment by aldarund** [comment]
`Please note that for upgrading Nuxt.js just changing version inside package.json is not enough. Please use yarn upgrade or npm upgrade so that the final directory structure of node_modules will be correct. In case of problems clean up node_modules and yarn.lock/package-lock.json. 

`
