### ISSUE TITLE
vite-node breaks with commit d15c472

### ISSUE THREAD

**Issue by Tahul** [nuxt/nuxt.js#14446]
### Environment

`v3.0.0-rc.6-27648546.d15c472`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-hk7jvp?file=package.json,nuxt.config.ts

Try moving back to 3.0.0-rc.6-27647394.5e62e0f in package.json and reinstalling dependencies, the project will work fine

### Describe the bug

```
[h3] [unhandled] H3Error: Cannot find module '/Users/yaelguilloux/Code/nuxt/docus/node_modules/@nuxt/vite-builder/dist/chunks/runtime/client.manifest.mjs' imported from /Users/yaelguilloux/Code/nuxt/docus/.nuxt/dist/server/client.manifest.mjs
    at createError (file:///Users/yaelguilloux/Code/nuxt/docus/node_modules/h3/dist/index.mjs:191:15)
    at Server.nodeHandler (file:///Users/yaelguilloux/Code/nuxt/docus/node_modules/h3/dist/index.mjs:381:21) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
```

This gets shown if booting with vite-node, site works fine if disabled
