### ISSUE TITLE
when I use typescript in layout file, error raise on page reload.

### ISSUE THREAD

**Issue by tooppoo** [nuxt/nuxt.js#800]
/path/to/home/layouts/homepage.vue
```
<template>
  <section id="app">
    <nuxt/>
  </section>
</template>

<script lang="ts">
import Vue from 'vue';
import Component from 'vue-class-component';

@Component
export default class HomepageLayout extends Vue {
}
</script>
```
/path/to/home/page/homepage/index.vue
```
<template>
  <section>test</section>
</template>

<script>
export default {
  layout: 'homepage'
}
</script>
```

I try to use typescriot preprocessor in `path/to/home/layouts/homepage.vue`.
On first access to `localhost:3000/homepage`, brower can show page correctly.
But I reload brower and following error is displayed.
```
Nuxt.js Error:

TypeError: this._init is not a function
    at Object.VueComponent [as _homepage] (/path/to/home/node_modules/vue/dist/vue.runtime.common.js:4167:12)
    at Vue$3.loadLayout (App.vue:49:0)
    at Vue$3.boundFn [as loadLayout] (/path/to/home/node_modules/vue/dist/vue.runtime.common.js:166:14)
    at Object._callee$ (.nuxt/server.js:87:13)
    at tryCatch (~/regenerator-runtime/runtime.js:65:14)
    at GeneratorFunctionPrototype.invoke [as _invoke] (~/regenerator-runtime/runtime.js:303:0)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (~/regenerator-runtime/runtime.js:117:0)
    at step (~/babel-runtime/helpers/asyncToGenerator.js:17:0)
    at server-bundle.js:1271:13
```

**Comment by Atinux** [comment]
Hi @tooppoo 

Can you create a reproduction by forking https://glitch.com/edit/#!/nuxt-hello-world?

**Comment by piyushchauhan2011** [comment]
Yeah, still happening! I think even without `ts` ( Typescript ), in-general `vue-class-component` with layouts is giving error. Here is the repo with bug reproduced (https://github.com/piyushchauhan2011/nuxt-component/tree/error/layout-class-component)

Maybe we are missing something in constructor or component class related to `child`, not sure though.

**Comment by jvbianchi** [comment]
It started to happen to me after I updated Typescript to v2.4
