### ISSUE TITLE
console error after upgrading from 2.8.1 to 2.9.1

### ISSUE THREAD

**Issue by nelsonlarocca** [nuxt/nuxt.js#6259]
### Version

[v2.9.1](https://github.com/nuxt.js/releases/tag/v2.9.1)

### Reproduction link

[https://notavailable.com](https://notavailable.com)

### Steps to reproduce

npm run dev

and I get

```'find_dp0' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\nuxt\bin\nuxt.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

### What is expected ?

some help 

### What is actually happening?

using npm version 6.11 and just upgraded nuxtjs version I got the above error

### Additional comments?

I just upgraded from 2.8.1 to 2.9.1 and as soon as 
npm run *
* = dev or build or start

the console drops the error above

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9662">#c9662</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Please try cleaning `node_modules` and lock file. That might fix this issue.

**Comment by nelsonlarocca** [comment]
Dear Pooya:

Didn’t work out

I’m doing some research now

 

Just to start

 

Error: Cannot find module 'C:\nuxt\bin\nuxt.js'

 

Is not a valid path !

**Comment by nelsonlarocca** [comment]
Updating

 

Creating a new app from scratch, lead to a lot of errors !

It seems an environment variable or something like that is not set, node_modules in particular ! since c:\@huxt should be c:\<my-app-path>\node_modules (for instance)

 

 

 

$ npx create-nuxt-app my-app

npx: installed 365 in 74.865s

 

create-nuxt-app v2.9.2

✨  Generating Nuxt.js project in my-app

? Project name my-app

? Project description Creating a NEW experience for both restaurants and their users

? Author name YaMenu

? Choose the package manager Npm

? Choose UI framework Vuetify.js

? Choose custom server framework None (Recommended)

? Choose Nuxt.js modules Progressive Web App (PWA) Support

? Choose linting tools ESLint, Prettier

? Choose test framework None

? Choose rendering mode Universal (SSR)

npm WARN deprecated @babel/polyfill@7.4.4: � As of Babel 7.4.0, this

npm WARN deprecated package has been deprecated in favor of directly

npm WARN deprecated including core-js/stable (to polyfill ECMAScript

npm WARN deprecated features) and regenerator-runtime/runtime

npm WARN deprecated (needed to use transpiled generator functions):

npm WARN deprecated

npm WARN deprecated   > import "core-js/stable";

npm WARN deprecated   > import "regenerator-runtime/runtime";

npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

 

 

> fibers@4.0.1 install C:\Projects\NUXT\my-app\node_modules\fibers

> node build.js || nodejs build.js

npm WARN deprecated @babel/polyfill@7.4.4: � As of Babel 7.4.0, this

npm WARN deprecated package has been deprecated in favor of directly

npm WARN deprecated including core-js/stable (to polyfill ECMAScript

npm WARN deprecated features) and regenerator-runtime/runtime

npm WARN deprecated (needed to use transpiled generator functions):

npm WARN deprecated

npm WARN deprecated   > import "core-js/stable";

npm WARN deprecated   > import "regenerator-runtime/runtime";

npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

'find_dp0' is not recognized as an internal or external command,

operable program or batch file.

 

 

> fibers@4.0.1 install C:\Projects\NUXT\my-app\node_modules\fibers

> node build.js || nodejs build.js

npm WARN deprecated @babel/polyfill@7.4.4: � As of Babel 7.4.0, this

npm WARN deprecated package has been deprecated in favor of directly

npm WARN deprecated including core-js/stable (to polyfill ECMAScript

npm WARN deprecated features) and regenerator-runtime/runtime

npm WARN deprecated (needed to use transpiled generator functions):

npm WARN deprecated

npm WARN deprecated   > import "core-js/stable";

npm WARN deprecated   > import "regenerator-runtime/runtime";

npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

'find_dp0' is not recognized as an internal or external command,

operable program or batch file.

internal/modules/c

 

> fibers@4.0.1 install C:\Projects\NUXT\my-app\node_modules\fibers

> node build.js || nodejs build.js

npm WARN deprecated @babel/polyfill@7.4.4: � As of Babel 7.4.0, this

npm WARN deprecated package has been deprecated in favor of directly

npm WARN deprecated including core-js/stable (to polyfill ECMAScript

npm WARN deprecated features) and regenerator-runtime/runtime

npm WARN deprecated (needed to use transpiled generator functions):

npm WARN deprecated

npm WARN deprecated   > import "core-js/stable";

npm WARN deprecated   > import "regenerator-runtime/runtime";

npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

'find_dp0' is not recognized as an internal or external command,

operable program or batch file.

internal/modules/cjs/loader.js:638

     throw err;

     ^

 

Error: Cannot find module 'C:\@nuxt\opencollective\bin\opencollective.js'

     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

     at Function.Module._load (internal/modules/cjs/loader.js:562:25)

     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)

     at startup (internal/bootstrap/node.js:283:19)

     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

 

 

> fibers@4.0.1 install C:\Projects\NUXT\my-app\node_modules\fibers

> node build.js || nodejs build.js

npm WARN deprecated @babel/polyfill@7.4.4: � As of Babel 7.4.0, this

npm WARN deprecated package has been deprecated in favor of directly

npm WARN deprecated including core-js/stable (to polyfill ECMAScript

npm WARN deprecated features) and regenerator-runtime/runtime

npm WARN deprecated (needed to use transpiled generator functions):

npm WARN deprecated

npm WARN deprecated   > import "core-js/stable";

npm WARN deprecated   > import "regenerator-runtime/runtime";

npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

'find_dp0' is not recognized as an internal or external command,

operable program or batch file.

internal/modules/cjs/loader.js:638

     throw err;

     ^

 

Error: Cannot find module 'C:\@nuxt\opencollective\bin\opencollective.js'

     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

     at Function.Module._load (internal/modules/cjs/loader.js:562:25)

     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)

     at startup (internal/bootstrap/node.js:283:19)

     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

npm

 

> fibers@4.0.1 install C:\Projects\NUXT\my-app\node_modules\fibers

> node build.js || nodejs build.js

npm WARN deprecated @babel/polyfill@7.4.4: � As of Babel 7.4.0, this

npm WARN deprecated package has been deprecated in favor of directly

npm WARN deprecated including core-js/stable (to polyfill ECMAScript

npm WARN deprecated features) and regenerator-runtime/runtime

npm WARN deprecated (needed to use transpiled generator functions):

npm WARN deprecated

npm WARN deprecated   > import "core-js/stable";

npm WARN deprecated   > import "regenerator-runtime/runtime";

npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

'find_dp0' is not recognized as an internal or external command,

operable program or batch file.

internal/modules/cjs/loader.js:638

     throw err;

     ^

 

Error: Cannot find module 'C:\@nuxt\opencollective\bin\opencollective.js'

     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

     at Function.Module._load (internal/modules/cjs/loader.js:562:25)

     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)

     at startup (internal/bootstrap/node.js:283:19)

     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN eslint-plugin-vue@5.2.3 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN vue-eslint-parser@5.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\watchpack\node_modules\fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

 

 

 

> fibers@4.0.1 install C:\Projects\NUXT\my-app\node_modules\fibers

> node build.js || nodejs build.js

 

> fibers@4.0.1 install C:\Projects\NUXT\my-app\node_modules\fibers

> node build.js || nodejs build.js

 

`win32-x64-64` exists; testing

Binary is fine; exiting

 

> my-app@1.0.0 lint C:\Projects\NUXT\my-app

> eslint --ext .js,.vue --ignore-path .gitignore . "--fix"

 

'find_dp0' is not recognized as an internal or external command,

operable program or batch file.

internal/modules/cjs/loader.js:638

    throw err;

    ^

 

Error: Cannot find module 'C:\eslint\bin\eslint.js'

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

    at Function.Module._load (internal/modules/cjs/loader.js:562:25)

    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)

    at startup (internal/bootstrap/node.js:283:19)

    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

 

�  Successfully created project my-app

 

  To get started:

 

        cd my-app

        npm run dev

 

  To build & start for production:

 

        cd my-app

        npm run build

        npm run start

**Comment by pi0** [comment]
Seems an error from your development environment. Are you using cygwin or wsl?

**Comment by nelsonlarocca** [comment]
Just got the terminal from git-scm.com

 

Just for your records, the problem just showed up after the ‘npm update’ updating nuxt

**Comment by nelsonlarocca** [comment]
Updating !

 

Tried a new installation in another machine and got right the same:

 

$ npx create-nuxt-app myapp

npx: installed 365 in 37.61s

 

create-nuxt-app v2.9.2

✨  Generating Nuxt.js project in myapp

? Project name myapp

? Project description My fantastic Nuxt.js project

? Author name Nelson La Rocca

? Choose the package manager Npm

? Choose UI framework Vuetify.js

? Choose custom server framework None (Recommended)

? Choose Nuxt.js modules Progressive Web App (PWA) Support

? Choose linting tools ESLint, Prettier

? Choose test framework None

? Choose rendering mode Universal (SSR)

npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

 

 

 

> fibers@4.0.1 install C:\Projects\NUXT\myapp\node_modules\fibers

> node build.js || nodejs build.js

 

`win32-x64-64` exists; testing

npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

'find_dp0' is not recognized as an internal or external command,

operable program or batch file.

 

 

> fibers@4.0.1 install C:\Projects\NUXT\myapp\node_modules\fibers

> node build.js || nodejs build.js

 

`win32-x64-64` exists; testing

 

> fibers@4.0.1 install C:\Projects\NUXT\myapp\node_modules\fibers

> node build.js || nodejs build.js

 

`win32-x64-64` exists; testing

Binary is fine; exiting

 

> core-js@2.6.9 postinstall C:\Projects\NUXT\myapp\node_modules\core-js

npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

'find_dp0' is not recognized as an internal or external command,

operable program or batch file.

internal/modules/cjs/loader.js:638

     throw err;

     ^

 

Error: Cannot find module 'C:\@nuxt\opencollective\bin\opencollective.js'

     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

     at Function.Module._load (internal/modules/cjs/loader.js:562:25)

     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)

     at startup (internal/bootstrap/node.js:283:19)

     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN eslint-plugin-vue@5.2.3 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN vue-eslint-parser@5.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\watchpack\node_modules\fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

 

 

 

> fibers@4.0.1 install C:\Projects\NUXT\myapp\node_modules\fibers

> node build.js || nodejs build.js

 

`win32-x64-64` exists; testing

Binary is fine; exiting

 

> core-js@2.6.9 postinstall C:\Projects\NUXT\myapp\node_modules\core-js

 

> myapp@1.0.0 lint C:\Projects\NUXT\myapp

> eslint --ext .js,.vue --ignore-path .gitignore . "--fix"

 

'find_dp0' is not recognized as an internal or external command,

operable program or batch file.

internal/modules/cjs/loader.js:638

    throw err;

    ^

 

Error: Cannot find module 'C:\eslint\bin\eslint.js'

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

    at Function.Module._load (internal/modules/cjs/loader.js:562:25)

    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)

    at startup (internal/bootstrap/node.js:283:19)

    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

 

�  Successfully created project myapp

 

  To get started:

 

        cd myapp

        npm run dev

 

  To build & start for production:

 

        cd myapp

        npm run build

        npm run start

**Comment by pimlie** [comment]
@nelsonlarocca Please try to format your posts properly as these are totally unreadable. I guess replying on github emails isnt the best when you add a lot of console output. I tried formatting one post but it didnt work, maybe you can do it.

Thanks :)

**Comment by nelsonlarocca** [comment]
IMPORTANT UPDATE:

Yesterday I upgraded npm before upgrading nuxt, today a new npm version was available.
This is the only warning I get AFTER upgrading npm to the latest version: 6.11.1

```
### npm WARN deprecated @babel/polyfill@7.4.4: � As of Babel 7.4.0, this
npm WARN deprecated package has been deprecated in favor of directly
npm WARN deprecated including core-js/stable (to polyfill ECMAScript
npm WARN deprecated features) and regenerator-runtime/runtime
npm WARN deprecated (needed to use transpiled generator functions):
npm WARN deprecated
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN eslint-plugin-vue@5.2.3 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-eslint-parser@5.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

**Comment by manniL** [comment]
I'm not sure if I can follow. Please edit your initial post with the correct issue and formatted code if the error persists. Then, ping me or any core team member here and we can reopen the issue
