### ISSUE TITLE
Attempting to integrate Jest with Nuxt.js

### ISSUE THREAD

**Issue by piyushchauhan2011** [nuxt/nuxt.js#1075]
Hi @Atinux and @eddyerburgh,

This is the first attempt to integrate Jest with Nuxt.js . I ran into couple of error related to `nuxt` library which I don't understand. It would be nice to have a look at the sample codebase here https://github.com/piyushchauhan2011/nuxt-with-jest .

Pros:

- Was able to test store and sample `.js` files
- I was also able to unit-test components
- Snapshot testing

![screen shot 2017-07-12 at 7 34 08 pm](https://user-images.githubusercontent.com/693487/28115844-2321bc98-6739-11e7-897f-b35f6a664108.png)

Broken:

- End to end testing

```
    ERROR in ./.nuxt/client.js
    Module build failed: Error: Cannot find module '../../package' from 'node.js'
        at Resolver.resolveModule (/Users/piyushchauhan/Documents/jirnexu/nuxt-with-jest/node_modules/jest-resolve/build/index.js:179:17)
        at Resolver._getVirtualMockPath (/Users/piyushchauhan/Documents/jirnexu/nuxt-with-jest/node_modules/jest-resolve/build/index.js:296:23)
        at Resolver._getAbsolutPath (/Users/piyushchauhan/Documents/jirnexu/nuxt-with-jest/node_modules/jest-resolve/build/index.js:279:10)
        at Resolver.getModuleID (/Users/piyushchauhan/Documents/jirnexu/nuxt-with-jest/node_modules/jest-resolve/build/index.js:252:31)
        at Runtime._shouldMock (/Users/piyushchauhan/Documents/jirnexu/nuxt-with-jest/node_modules/jest-runtime/build/index.js:574:37)
        at Runtime.requireModuleOrMock (/Users/piyushchauhan/Documents/jirnexu/nuxt-with-jest/node_modules/jest-runtime/build/index.js:402:14)
```

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c936">#c936</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @piyushchauhan2011 

Great job :)
We will work on it after 1.0 release, it's really nice to see someone taking the lead on this!

CC @pi0

**Comment by piyushchauhan2011** [comment]
Currently, we use a mix of `jest` and `ava` for unit and end-to-end testing 😄  which obviously isn't a good solution but working for now, as we needed something quick for CircleCI to output some level of coverage. It would be nice to have `jest` integration natively or through `nuxt modules` @Atinux @pi0

**Comment by piyushchauhan2011** [comment]
As compared to ava I also like the integration of jest with vscode, very helpful during development

![screen shot 2017-07-13 at 11 43 56 am](https://user-images.githubusercontent.com/693487/28149518-bd287be2-67c0-11e7-89a3-225861cb6df5.png)

**Comment by piyushchauhan2011** [comment]
Updated the repo with latest `rc3`. Love to see the dynamic components working now 💯  . Hopefully we will get testing going after `1.0` release. `:excited:`

**Comment by pi0** [comment]
@piyushchauhan2011 So excited too 👍  I'll open a new issue on repo for some updates.

**Comment by thejones** [comment]
Any updates on this issue? Was anybody able to get the E2E testing working with Jest and the new Nuxt Builder/ webpack issues?

**Comment by kartojal** [comment]
I got a way to test Nuxt applications e2e using Testcafe, after writing a module to support Nuxt. Maybe you find it useful. You can check the **package.json** and the **test** directory to get a clue how to get it working.
testcafe-nuxt-selectors: https://github.com/kartojal/testcafe-nuxt-selectors
testcafe library: https://devexpress.github.io/testcafe/

**Comment by lukasborawski** [comment]
@kartojal any conclusions after testing with testcafe and nuxt? any problems, obstacles, pros, cons?

**Comment by kartojal** [comment]
The only obstacle i found, after creating a module for supportig nuxt, was
learning another test framework, with a small learning curve. But is
working really good, helps me to test the nuxt app end 2 end, in a variety
of browsers and in a visual way (if needed, the tests can run headless too).
2017-10-03 12:30 GMT+02:00 Lukas Borawski <notifications@github.com>:

**Comment by alidcastano** [comment]
Not sure if this setup still works. I tried updating it for Nuxt 1.0 release but I'm getting `cannot find ./types/standard'` resolver error.

@piyushchauhan2011  have you tried it?

**Comment by alidcastano** [comment]
Hey guys, I created a zero-configuration test runner for Nuxt.js using Jest and Puppeteer: https://github.com/studbits/nuxt-jest-puppeteer

Hopefully it helps!

**Comment by husayt** [comment]
@alidcastano this looks really cools. Will be great to get it polished, and get more people using it in order  to get all the best practices in. I suggest to add a sample project using this to nuxt examples [here](https://github.com/nuxt/nuxt.js/tree/dev/examples).

**Comment by manniL** [comment]
cc @clarkdo I think this issue can be closed :relaxed:
