### ISSUE TITLE
Regression? Error: Cannot find module 'pug'

### ISSUE THREAD

**Issue by homerjam** [nuxt/nuxt.js#1887]
There seems to be a regression since https://github.com/nuxt/nuxt.js/commit/6a1fd757c620b2d1791764cf5b042c8dc291dcf1

My guess is that it's to do with an update to vue-template-renderer. I've tried my best to dig into it to no avail : (

The following error occurs when running `npm run dev`:

```
Error: Cannot find module 'pug'

  - module.js:11 require
    internal/module.js:11:18

  - consolidate.js:825
    [lib]/[nuxt]/[consolidate]/lib/consolidate.js:825:33

  - consolidate.js:144
    [lib]/[nuxt]/[consolidate]/lib/consolidate.js:144:5

  - debuggability.js:300 Promise._execute
    [lib]/[nuxt]/[bluebird]/js/release/debuggability.js:300:9

  - promise.js:483 Promise._resolveFromExecutor
    [lib]/[nuxt]/[bluebird]/js/release/promise.js:483:18

  - promise.js:79 new Promise
    [lib]/[nuxt]/[bluebird]/js/release/promise.js:79:10

  - consolidate.js:137 promisify
    [lib]/[nuxt]/[consolidate]/lib/consolidate.js:137:10

  - consolidate.js:821 Function.exports.pug.render
    [lib]/[nuxt]/[consolidate]/lib/consolidate.js:821:10

  - preprocessor.js:26 Object.module.exports
    [lib]/[nuxt]/[vue-loader]/lib/template-compiler/preprocessor.js:26:20

  - LoaderRunner.js:119 LOADER_EXECUTION
    [lib]/[nuxt]/[loader-runner]/lib/LoaderRunner.js:119:14

  - LoaderRunner.js:120 runSyncOrAsync
    [lib]/[nuxt]/[loader-runner]/lib/LoaderRunner.js:120:4

  - LoaderRunner.js:229 iterateNormalLoaders
    [lib]/[nuxt]/[loader-runner]/lib/LoaderRunner.js:229:2

  - LoaderRunner.js:218 iterateNormalLoaders
    [lib]/[nuxt]/[loader-runner]/lib/LoaderRunner.js:218:10
```

I noticed when trying to debug this the `pify` module is removed from dependencies in `start/package.json` - incomplete switch to/from Bluebird maybe?

**Comment by homerjam** [comment]
Appears fixed now, closing.

**Comment by rvanzon** [comment]
sorry, to reply on this old issue. But I am facing this problem with nuxt-edge. Do you know what fixed it?
