### ISSUE TITLE
Nuxt is not a constructor error on latest version (1.0.0-rc3)

### ISSUE THREAD

**Issue by kathirvGitHub** [nuxt/nuxt.js#1225]
Hi, I am using the nuxt socket example and after upgrading my nuxt to recent version I keep receiving error on this line of code in server.js

let config = require('./nuxt.config.js')
const nuxt = new Nuxt(config)

Stack trace:

C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\server.js:18
const nuxt = new Nuxt(config)
             ^
TypeError: Nuxt is not a constructor
    at Object.<anonymous> (C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\server.js:18:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

The same code works fine on with NUXT version 0.10.7

**Comment by benfavre** [comment]
Same thing here pretty much : UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_2_nuxt___default.a is not a constructor
Currently running ok on : v1.0.0-alpha.4

**Comment by KonstantinVlasov** [comment]
[duplicate](https://github.com/nuxt/nuxt.js/issues/1219)

**Comment by kathirvGitHub** [comment]
Hi, As suggested by @benfavre I tried with v1.0.0-alpha.4 the same code works fine, so its only the latest version I have issue. 

So as suggested by @KonstantinVlasov , I tried to follow the example of using the code below

const { Nuxt, Builder } = require('nuxt')

// Import and set nuxt.js options
let config = require('./nuxt.config.js')
config.dev = !(process.env.NODE_ENV === 'production')

let nuxt = new Nuxt(config)

// Start build process (only in development)
if (config.dev) {
  new Builder(nuxt).build()
}

The syntax error is gone, but my index.vue doesn't load anymore with error

Error: Cannot find module 'es6-promise\auto' from 'C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1'
    at Function.module.exports [as sync] (C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\resolve\lib\sync.js:40:15)
    at r (C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\vue-server-renderer\build.js:7741:44)
    at Object.<anonymous> (webpack:/external "es6-promise/auto":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap c56950b3a6ef8f7b0bb4:25:0)
    at Object.<anonymous> (server-bundle.js:1471:75)
    at __webpack_require__ (webpack:/webpack/bootstrap c56950b3a6ef8f7b0bb4:25:0)
    at Object.<anonymous> (server-bundle.js:1002:65)
    at __webpack_require__ (webpack:/webpack/bootstrap c56950b3a6ef8f7b0bb4:25:0)
    at server-bundle.js:92:18
    at Object.<anonymous> (server-bundle.js:95:10)
    at evaluateModule (C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\vue-server-renderer\build.js:7747:21)
    at C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\vue-server-renderer\build.js:7805:18
    at C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\vue-server-renderer\build.js:7797:14
    at Object.renderToString (C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\vue-server-renderer\build.js:7951:9)
    at P (C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\pify\index.js:49:6)
    at Object.<anonymous> (C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\pify\index.js:11:9)
    at Object.ret [as renderToString] (C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\pify\index.js:72:32)
    at Renderer._callee7$ (C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\nuxt\lib\core\renderer.js:325:41)
    at tryCatch (C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\nuxt\node_modules\regenerator-runtime\runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\nuxt\node_modules\regenerator-runtime\runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\nuxt\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\kpandurangan\Desktop\NodeJS\nuxt-sample1\node_modules\nuxt\dist\nuxt.js:852:30)

can you please advise, the only thing I changed is the server.js nothing else. which works when I revert release back to alpha.4 and server.js using the nuxt code as before

**Comment by Twisterking** [comment]
Just had the same error on Windows with RC3:
```
uncaughtException stack TypeError: Nuxt is not a constructor
```
Re-installing Alpha.5 solved the problem for now!

**Comment by pi0** [comment]
Please see [RC3 Release Notes](https://github.com/nuxt/nuxt.js/releases/tag/1.0.0-rc3). You have to require Nuxt like this: https://github.com/nuxt/nuxt.js/blob/dev/examples/custom-server/server.js

**Comment by kathirvGitHub** [comment]
@pi0 : I followed the RC3 release notes and adapted the new code for calling NUXT programmatically already yesterday, as I mentioned above after the new code, the syntax error is now gone but my index.vue won't load anymore with es6-promise\auto error.

**Comment by pi0** [comment]
@kathirvGitHub Probably the exact problem isn't with `es6-promise`. Would you please provide more details about error you get?

**Comment by kathirvGitHub** [comment]
@pi0  : So I adapt the code in server.js . Then when start up "npm run dev", and go to localhost in my chrome, i just get this 

![image](https://user-images.githubusercontent.com/28948343/28820750-1165ae22-76b3-11e7-9961-d88614d567f1.png)

and on my console, i see this message

![image](https://user-images.githubusercontent.com/28948343/28820765-210d0bea-76b3-11e7-9f62-32c13c3ae809.png)

**Comment by Atinux** [comment]
@kathirvGitHub please `rm -rf node_modules/` and do again `npm install`, it should fix your issue.

**Comment by kathirvGitHub** [comment]
@Atinux  : Thanks, I tried that, but no luck. Still getting the same error. I removed everything on my index.vue to see if anything is causing the issue, and just have a simple text in <h1> but it still errors. I think this is something related to the server.js . I have another test project which is a simple one without server.js works fine, the project which uses socket related calls and server.js has issue.

**Comment by pi0** [comment]
@kathirvGitHub With upcoming `rc4` that `[object Promise]` will be replaced with exact error helping to find what's exact problem :)

**Comment by kathirvGitHub** [comment]
Solved the issue. Created a new project from scratch with starter template, and copied the code related to logic into the new project and everything started to work fine. So something inside old .nuxt folder caused it. Thanks everyone for your time and help.

**Comment by prasadsilva** [comment]
I ran into the same issue. Yarn was installing es6-promise 3.1.x even though rc3 requires 4.1.1. My solution was to explicitly require 4.1.1 in my project's package.json (devDeps).

**Comment by pi0** [comment]
@prasadsilva Would you please give the result of `yarn why es6-promise` ?
