### ISSUE TITLE
Error while initializing app TypeError: parentVal.concat is not a function

### ISSUE THREAD

**Issue by lucpotage** [nuxt/nuxt.js#3957]
### Version

[2.0.0](https://github.com/nuxt.js/releases/tag/2.0.0)

### Reproduction link

[https://nuxtjs.org](https://nuxtjs.org)

### Steps to reproduce

Upgrade a project to Nuxt 2.0.0.

### What is expected ?

No error.

### What is actually happening?

Hello. I get the following error that is not easy to understand and debug:

```
[nuxt] Error while initializing app TypeError: parentVal.concat is not a function
    at mergeHook (commons.app.js:10224)
    at mergeField (commons.app.js:10485)
    at mergeOptions (commons.app.js:10476)
    at Function.Vue.extend (commons.app.js:13793)
    at sanitizeComponent (app.js:4688)
    at _callee$ (app.js:4757)
    at tryCatch (commons.app.js:4154)
    at Generator.invoke [as _invoke] (commons.app.js:4388)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/_nuxt/commons.app.js:4206:21)
    at asyncGeneratorStep (commons.app.js:33)
```

It seems to be part of the Vue.js framework. Any idea what could cause this in my code? A module, a Vue plugin, an external lib?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7819">#c7819</a>)</em></sub></div>

**Comment by jcardell** [comment]
Same is happening to me after I updated my dependencies.

**Comment by manniL** [comment]
It's a bug in `nuxt-i18n` after the last `vue-meta` release.

Use `seo: false` in the module options or downgrade `vue-meta` by one minor version to temporary work around the issue.

**Comment by jcardell** [comment]
I can confirm that turning seo to false fixes the issue for now.

I tried to downgrade vue-meta to 1.5.3 and other issues started happening.

**Comment by lucpotage** [comment]
Wow, thank you for the quick workaround!

**Comment by Harry72** [comment]
Yes - after an upgrade of my test project from 1.0.0 to 2.0.0 (same from 1.0.0 to 1.4.x versions) i also figgered out that nuxt-i18n causes this error. Setting seo to false fixed this error.

**Comment by billyshena** [comment]
Any ideas how to fix it without "seo:false" ?
Otherwise, do we have to manually add the alternate url to every page ?

Best,

**Comment by begueradj** [comment]
@manniL 
In my nuxt.config.js file, I tried:

```
modules: [
    ['nuxt-i18n', {
      seo:false
    }]
```
But this does not fix the issue, am I doing this the wrong way maybe? Thank you
Billal Begueradj

**Comment by manniL** [comment]
@begueradj There might be another reason as well. Try downgrading vue-meta to 1.5.3

**Comment by begueradj** [comment]
@manniL Thank you for the quick response.

I am not using vue-meta in my Nuxt.js application. All what I did is installing nuxt-i18n and set it as I showed (according to the official [documentation](https://nuxt-community.github.io/nuxt-i18n/setup.html)), and then when I type `npm run dev` I get the same error above.

**Comment by manniL** [comment]
@begueradj You use vue-meta automatically because it's included in Nuxt. Please try it ;)

**Comment by manniL** [comment]
Resolved with `vue-meta@1.5.5`

**Comment by svnba** [comment]
Updating the dependency **nuxt** from `2.0.0` to `2.2.0` did it.

**Comment by manniL** [comment]
Shouldn't be related to a nuxt upgrade as nuxt doesn't pin versions. A `yarn upgrade` or `npm update` would be sufficient.
