### ISSUE TITLE
vue-app targets don't work after migrating to 2.0.0

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#4010]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://codesandbox.io/s/jjry4xn7x5](https://codesandbox.io/s/jjry4xn7x5)

### Steps to reproduce

Add this to `nuxt.config.js`

```js
 build: {
    babel: {
      presets({ isServer }) {
        return [
          [
            "vue-app",
            { targets: isServer ? { node: "10.3.0" } : { chrome: 69 } }
          ]
        ];
      }
    }
  }

```

Run `npm run dev`

### What is expected ?

Application should compile

### What is actually happening?

`Module build failed (from ./node_modules/babel-loader/lib/index.js): TypeError: this.setDynamic is not a function at PluginPass.pre (/sandbox/node_modules/babel-plugin-transform-runtime/lib/index.js:31:12) at transformFile 
`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7869">#c7869</a>)</em></sub></div>

**Comment by aldarund** [comment]
There no vue-app preset in nuxt 2. Vue-app is for babel 6 while nuxt 2 use babel 7.
You need to use  " "@nuxtjs/babel-preset-app" 
See updated codesandbox https://codesandbox.io/s/1r6ll5pojl
