### ISSUE TITLE
`@nuxt/test-utils-edge` doesn't work with `vitest` v0.24.0 or later

### ISSUE THREAD

**Issue by e-chan1007** [nuxt/nuxt.js#15404]
### Environment

- Nuxt Version:     `3.0.0-rc.13`
- `@nuxt/test-utils-edge` Version:    `latest(3.0.0-rc.14-27796957.b60f136)`
- Vitest Version:    `^0.24.0`

### Reproduction

https://stackblitz.com/edit/github-raxmub-uprd1m?file=package.json

### Describe the bug

With `vitest@^0.24.0` or the latest `0.25.0`, `nuxt test` will fail, and the following error occurs:
```
Cannot find module '/path/to/project/node_modules/vitest/dist/node.mjs' imported from /path/to/project/node_modules/@nuxt/test-utils-edge/dist/index.mjs
```

We should import `vitest/dist/node.js` rather than `vitest/dist/node.mjs`.

### Additional context

The extension once changed to `.mjs` in https://github.com/vitest-dev/vitest/commit/692ad34 , but in https://github.com/vitest-dev/vitest/pull/1411 it was reverted and now using `.js`.

[This PR(vitest-dev/vitest#1411)](https://github.com/vitest-dev/vitest/pull/1411) was merged and released as `v0.24.0` so using `v0.23.4` or former can also resolve this issue, but I can't see it as the best way.
