### ISSUE TITLE
Error: Cannot find module 'vue' on Heroku;

### ISSUE THREAD

**Issue by ajcpwnz** [nuxt/nuxt.js#467]
Hello there.
I've created a new app using starter template, it's almost empty, works fine on local machine and gives me this error on heroku: 
<img width="901" alt="screen shot 2017-03-28 at 11 23 02 pm" src="https://cloud.githubusercontent.com/assets/16022609/24425613/7883bbde-140d-11e7-958d-5672d4359466.png">
I have another nuxt app there, with older nuxt version and it works as intended, so I don't know what  it could be.

Adding `package.json`, maybe it helps.
```js
 "name": "<>",
  "version": "1.0.0",
  "description": "<>",
  "author": "<>",
  "private": true,
  "dependencies": {
    "css-loader": "^0.27.3",
    "firebase": "^3.7.3",
    "nuxt": "latest",
    "vue": "^2.2.6"
  },
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "",
    "precommit": "npm run lint",
    "heroku-postbuild": "npm run build"
  },
  "devDependencies": {
    "node-sass": "^4.5.0",
    "sass-loader": "^6.0.2",
    "webpack": "^2.2.1"
  }
```

**Comment by Tibfib** [comment]
I'm seeing the same issue here. It worked fine with v0.9.x but since updating to v0.10.0 I've been getting this as well.

**Comment by ajcpwnz** [comment]
Don't want to be an asshole here, but since I could not do anything about this bug in my project, i've put it to some test. 
I've deployed empty application to heroku. The only change I did was adding  `"heroku-postbuild": "npm run build"` line to `package.json` and gitignoring .idea folder. 
ENV vars are ofcourse set as intended: 

<img width="841" alt="screen shot 2017-03-29 at 4 18 36 pm" 
src="https://cloud.githubusercontent.com/assets/16022609/24456262/288b11ac-149b-11e7-82e3-6ad9d08d36b4.png">


 Repo which I deployed to double-check is [here](https://github.com/ajcpwnz/nuxt-heroku-test). 
Sadly, this error persirst even with blank app. :( Thats why I suspect this might be an issue with nuxt or its dependencies itself, though I don't have any ideas how could I help fixing it without diving into nuxt core :(.

Hope this helps.

**Comment by ausir0726** [comment]
I can confirm `0.10.x` can't be deployed to heroku with empty nuxt/starter template .
I tried it today , and got same error .

console have show some dependence warning/error , but I lost that information .

**Comment by paulstraw** [comment]
👋 Hey all, I believe this is actually a duplicate of #462. The solution in that thread worked for me on Heroku. Best of luck!

**Comment by ajcpwnz** [comment]
@paulstraw Yup, that worked for me too, thanks.
Hope it gets fixed by default in future releases.
