### ISSUE TITLE
webpack alias not working

### ISSUE THREAD

**Issue by IRoninCoder** [nuxt/nuxt.js#2793]
Here's the extension as suggested in community [here](https://github.com/nuxt/nuxt.js/issues/124):
```
module.exports = {
  /* Headers of the page */
  head: {
    title: '{{ name }}',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '{{ description }}' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /* Customize the progress bar color */
  loading: { color: '#3B8070' },
  /* build stuff */
  build: {
    extend (config, { isDev, isClient }) {
        config.resolve = module.resolve || {}
        config.resolve.alias = module.resolve.alias || {}
        config.resolve.alias['@components']= './components/'
    }
  }
}
```
And here's the not so lucky output when running `npm run-script build`:

```
ERROR in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":false,"presets":[["my app path//node_modules//babel-preset-vue-app//dist//index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue
Module not found: Error: Can't resolve '@components/AppLogo.vue' in 'my app path\pages'
 @ ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":false,"presets":[["my app path//node_modules//babel-preset-vue-app//dist//index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue 26:0-46
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
```
Any ideas on what's going on? I noticed a couple of things while battling this:

1. There are no `resolve` or `alias` objects, so they have to be added altogether.
2. Replacing the `@` with `~` does not help.
3. If instead of `./components`, `path.resolve(__dirname, './components/')` or `path.join(__dirname, './components/')` are used still would not work.

Using nuxt 1.3.0 which uses webpack 3.10.0 so I'm confused as to what could be wrong here. Also using windows 10.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2426">#c2426</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
Hi @IRoninCoder,

For this case you do not need an alias, just use `~/components/`

But if you want to create an alias, follow the example:

```js
module.exports = {
    build: {
        extend (config) {
            config.resolve.alias['myAlias']= path.join(this.options.srcDir, 'myPath')
        }
    }
}
```

see #1834

**Comment by rnenjoy** [comment]
Tried all kinds of aliases, nothing is working in nuxt 2.0 inside serverMiddlewares

**Comment by dkushner** [comment]
I am also having great difficulty resolving custom aliases from my components. Can anyone clarify what is happening here?

```
config.plugins.push(new webpack.ProvidePlugin({
    'THREE': 'three'
}))

config.resolve.alias['three/OrbitControls'] = path.join(this.options.srcDir, 'node_modules/three/examples/js/controls/OrbitControls.js')
config.resolve.alias['three/DRACOLoader'] = path.join(this.options.srcDir, 'node_modules/three/examples/js/loaders/DRACOLoader.js')
config.resolve.alias['three/GLTFLoader'] = path.join(this.options.srcDir, 'node_modules/three/examples/js/loaders/GLTFLoader.js')
```

I have also tried joining to `this.options.rootDir` with no real change. The error occurs when I try to actually load the page, it tells me:

```
{ Error: Cannot find module 'three/GLTFLoader' from '<projectDirectory>'
```

**Comment by ricardogobbosouza** [comment]
It works for me...

**nuxt.config.js**
```js
const path = require('path');

module.exports = {
  build: {
    extend (config) {
      config.resolve.alias['~three/OrbitControls']= path.join(this.options.rootDir, 'node_modules/three/examples/js/controls/OrbitControls.js');
    }
  }
}
```

**pages/index.vue**
```vue
<template>

</template>

<script>
import mod from '~three/OrbitControls';

export default {

}
</script>
```
