### ISSUE TITLE
nuxt.js version 0.10.x problems with ava testing

### ISSUE THREAD

**Issue by piyushchauhan2011** [nuxt/nuxt.js#784]
I'm trying to do testing integration with nuxt.js by following the guide/documentation on nuxt website. I also had a look in the example `with-ava` directory. But it seems to be using `0.9.x` package.

The error after running the `yarn test` is:

```javascript
Promise { <pending> }

  1 failed

  Init Nuxt.js
  /Users/piyushchauhan/Documents/jirnexu/hello/test/index.test.js:19

   18:   console.log(nuxt)
   19:   await nuxt.build()
   20:   server = new nuxt.Server(nuxt)

  Rejected promise returned by test

  Rejection reason:

    [TypeError: nuxt.build is not a function]

  Test.<anonymous> (test/index.test.js:19:14)
  step (test/index.test.js:18:191)
  Test.<anonymous> (test/index.test.js:18:99)
  Test._ava2.default.before [as fn] (test/index.test.js:11:1)

error Command failed with exit code 1.
```

Are the methods like `build` and `Server`, `renderRoute` got removed from `Nuxt` ?

**Comment by piyushchauhan2011** [comment]
Sorry for above realised that running `vue init nuxt/starter <project-name>` gives `nuxt: latest` in package.json. Made changes to `nuxt: ^0.10.6` and it works.

Not sure, why this is happening with `1.0.0-alpha`.

**Comment by piyushchauhan2011** [comment]
Any way if we can make the `ava` work with `1.0.0-alpha` ? Sorry for re-opening this issue!

**Comment by piyushchauhan2011** [comment]
Ahh, I figured something that might be useful here.

```javascript
const rootDir = resolve(__dirname, '..')
let config = {}
try { config = require(resolve(rootDir, 'nuxt.config.js')) } catch (e) {}
config.rootDir = rootDir // project folder
config.dev = false // production build
new Nuxt(config).then(nuxt => {
  // We keep the nuxt and server instance
  // So we can close them at the end of the test
  let server = null

  // Init Nuxt.js and create a server listening on localhost:4000
  test.before('Init Nuxt.js', async t => {
    await nuxt.build()
    server = new nuxt.Server(nuxt)
    server.listen(4000, 'localhost')
  })

  // Example of testing only generated html
  test('Route / exits and render HTML', async t => {
    let context = {}
    const { html } = await nuxt.renderRoute('/', context)
    t.true(html.includes('<h1>Home page</h1>'))
  })

  // Close server and ask nuxt to stop listening to file changes
  test.after('Closing server and nuxt.js', t => {
    server.close()
    nuxt.close()
  })
})
```

The above code works as the issue https://github.com/nuxt/nuxt.js/issues/754 describing the breaking changes suggest to enclose in a `.then` block.

Not sure if there is a better way!

**Comment by sudhir456** [comment]
Still not resolved for me. getting this error. (img attached)
![ava error](https://user-images.githubusercontent.com/22912682/32051312-c4c254e6-ba71-11e7-8e70-29e7502b90b8.png)

**Comment by sudhir600** [comment]
Still not resolved for me. getting this error. (img attached)
![ava error](https://user-images.githubusercontent.com/22912682/32051312-c4c254e6-ba71-11e7-8e70-29e7502b90b8.png)

**Comment by gangsthub** [comment]
@sudhir600, that "SyntaxError" happens because you have to enable babel compilation: to ES6 or similar. In your package.json: (This is a way to do it, but not the only one)

```
"ava": {
    "require": [
      "babel-polyfill"
    ]
    ...
}
```

Maybe you have `babel-polyfill` already installed. If not, `npm i babel-polyfill`
