### ISSUE TITLE
Uncaught TypeError: __webpack_require__(...) is not a function

### ISSUE THREAD

**Issue by RSchwan** [nuxt/nuxt.js#1410]
After upgrading from nuxt 1.0.0-rc3 to 1.0.0-rc4 I get this error. The error only occurs client side, ssr is fine.

![image](https://user-images.githubusercontent.com/9384498/29450524-51d94d7a-83ff-11e7-8fa7-f8b7dab0f04d.png)

I also reinstalled alle dependencies but it doesn't help. The weird thing is that it only occurs in development. If I build for production and run it there is no error.

**Comment by RSchwan** [comment]
I found the issue. I had something to do with `@nuxtjs/pwa`. If you hard refresh the browser it works.
